### ISSUE TITLE
Feature: ui-dropdown

### ISSUE THREAD

**Issue by awkay** [untangled-web/untangled-components#10]
There is an initial version in dropdowns namespace. Needs:

- Styling options (color, for example)
- Alternate style support for top-level look
- Separators?
- Other features/

**Comment by awkay** [comment]
We are also going to rename these menus. The things labeled menus in the css are really tabs.

**Comment by awkay** [comment]
@stephenway All CLJS dropdown things renamed to menu. CSS classes still need renamed.

**Comment by stephenway** [comment]
CSS classes have been renamed.
