### ISSUE TITLE
Calendar needs CSS work

### ISSUE THREAD

**Issue by awkay** [untangled-web/untangled-components#19]
Calendar is almost done, but it needs:

Fix the CSS so the overlay is properly aligned. This will probably require changing the React factory so that you pass in an element to render as the toggle control. E.g. like an icon or button.

Visual regression card

**Comment by awkay** [comment]
@stephenway could you work with me on this to finalize the component?

**Comment by stephenway** [comment]
@awkay I fixed the positioning to not center align.

**Comment by awkay** [comment]
@stephenway there is more to do

**Comment by stephenway** [comment]
We finished this a few days ago. Closing
