### ISSUE TITLE
Mangled cascade output

### ISSUE THREAD

**Issue by stephenway** [untangled-web/untangled-components#4]
Finally got some time to test this out and really love how it's coming along. I did notice that when writing some complex components that the CSS output does change property order from source order which can affect things like property fallbacks.

**Example source**

``` clojure
:all                'revert
:background-color   "#fff"
:border             "1px solid #b3b2a8"
:border-radius      "4px"
:box-shadow         "0 0 0 #000"
:display            'flex
:-ms-flex-direction 'row
:flex-direction     'row
:-ms-flex-wrap      'wrap
:flex-wrap          'wrap
:height             'auto
:margin-bottom      "6px"
:overflow-x         'hidden
:position           'relative
:transition         "box-shadow .1s ease-in-out"
:width              "100%"
:z-index            '1
```

**Example output**

``` clojure
  width: 100%;
  height: auto;
  -ms-flex-direction: row;
  border: 1px solid #b3b2a8;
  flex-direction: row;
  position: relative;
  z-index: 1;
  flex-wrap: wrap;
  margin-bottom: 6px;
  box-shadow: 0 0 0 #000;
  overflow-x: hidden;
  background-color: #fff;
  border-radius: 4px;
  display: flex;
  all: revert;
  transition: box-shadow .1s ease-in-out;
  -ms-flex-wrap: wrap;
```

**Comment by awkay** [comment]
Hm. This probably belongs on the om-css project?

Our css support is really Garden underneath. Could you give a concise example on the css project and we can discuss it there?

**Comment by stephenway** [comment]
Ahh ok, reposted [there](https://github.com/ladderlife/om-css/issues/38). Thanks

**Comment by awkay** [comment]
and note that it is untangled/om-css, not anmonterio's version
